<div class="section section-basic">
    <div class="container">
        <div class="title m-0">
            <a role="button" href="<?php echo $this->url(['module'=>'default','controller'=>'index','action'=>'nuevo'],null,true)?>" class="preloading text-white float-right btn btn-primary btn-round"><i class="fas fa-plus"></i> Ingresar siniestro</a>
            <h2>Mis siniestros</h2>
        </div>
        <div class="table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100% margin-top: -30px;">
                <thead>
                    <tr>
                        <th>Nº de Siniestro</th>
                        <th>Compañia</th>
                        <th>Asegurado</th>
                        <th>DNI</th>
                        <th class="text-right">Monto</th>
                        <th class="text-center">Fecha de ingreso</th>
                        <th class="text-center">Estado</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->sinisters as $sinister):?>
                    <tr>
                        <td><b><?php echo $sinister["si_number"];?></b></td>
                        <td><?php echo $sinister["co_name"];?></td>
                        <td><?php echo $sinister["si_fullname"];?></td>
                        <td><?php echo $sinister["si_document"];?></td>
                        <td class="text-right nowrap" nowrap="nowrap"><b>$ <?php echo number_format($sinister["si_amount"],0,',','.');?></b></td>
                        <td class="text-center"><?php echo date('d/m/Y', strtotime($sinister["si_date"])) ;?></td>
                        <td class="text-center"><?php echo $sinister["status_label"];?></td>
                        <td class="text-center">
                            <a rel="tooltip" class="preloading" data-original-title="Detalle" href="<?php echo $this->url(['module'=>'default','controller'=>'index','action'=>'siniestro','id'=>$sinister["si_id"]],null,true);?>">
                                <i class="fa fas fa-eye fa-1x text-primary"></i>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach ;?>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#datatable').DataTable({
            "aaSorting": [],
            "bLengthChange" : false,
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'
            },
        });
    } );
</script>