<div class="clearfix"></div>

<div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Actividades
            <?php if ($this->formDisabled != true): ?><a href="javascript:openActivity();"><span class="glyphicon glyphicon-plus pull-right"></span></a><?php endif; ?>
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-condensed replacement">
                <thead>
                    <tr>
                        <th>Descripción</th>
                        <th>Fecha</th>
                        <th>Usuario</th>
                    </tr>
                </thead>
                <tbody id="act_id">
                    <?php
                    foreach ($this->sinister_activities as $act):
                        ?>
                        <tr>
                            <td><?php echo $act["act_observation"]; ?></td>
                            <td><?php echo date("d-m-Y H:i", $act["act_created"]); ?></td>
                            <td><?php echo $act["ad_name"] . " " . $act["ad_last"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<script>
    function openActivity() {
        var type = 'ajax';
        var title = 'Registrar Actividad';
        var footer = 'false';
        var url = '<?php echo $this->url(array('module' => 'admin', 'controller' => 'sinister', 'action' => 'addactivity')); ?>';
        var w = '50%';
        var h = '350px';
        openModalScript(type, title, footer, url, w, h);
    }
    function writeActivity(text){
        $("#act_id").append('<tr>\n\
            <td><input type="hidden" name="new_activity[]" value="'+text+'">'+text+'</td>\n\
            <td>Ahora</td>\n\
            <td><?php echo $this->loginInfo['ad_name']." ".$this->loginInfo['ad_last'];?></td>\n\
            ');
    }
</script>