<div class="clearfix"></div>
<div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <label>Observaciones</label>
                <textarea class="form-control" name="activity" id="activity"></textarea> 
            </div>
            <div class="btn-group">
                <button class="btn btn-default" type="button" onclick="closeModal();">Cancelar</button>
                <button class="btn btn-info" type="button" onclick="send();">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<script>
    function send() {
        if ($('#activity').val().length > 0) {
            writeActivity($('#activity').val());
            closeModal();
        }
    }
</script>