<div class="clearfix"></div>
<div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Marcar como Entregado
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label>Nº de Factura </label>
                <textarea class="form-control" name="si_number_id" id="si_number_id"></textarea> 
            </div>
            <div class="btn-group">
                <button class="btn btn-default" type="button" onclick="closeModal();">Cancelar</button>
                <button class="btn btn-info" type="button" onclick="send();">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<script>
    function send() {
        $.post("<?php echo $this->url(array()); ?>",
                {
                    si_number_id: $("#si_number_id").val()
                })
                .done(function(data) {
                    if (data.length == 0) {
                        location.reload();
                    }
                });
    }
</script>