<?php if ($this->parameters["popup"] == false) : ?>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">Inicio</a></li>
        <li class="active">Regístrate</li>
    </ol>
<?php endif; ?>
<?php if ($this->response) { ?>
    <p class="text-danger text-center"><?php echo $this->response ?></p>
<?php } ?>
<?php if ($this->parameters["popup"] == true): ?>
    <div class="col-xs-12">
    <?php else: ?>
        <div class="col-lg-4 col-lg-offset-4 col-xs-12">
        <?php endif; ?>
        <div class="alert alert-danger" style="display: none;"></div>
        <div class="alert alert-success" style="display: none;"></div>
        <input type="hidden" name="fox_id" id="fox_id" value="<?php echo $this->result["fox_id"] ?>">
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Nombre *</label>
                <input type="text" class="form-control" id="name" name="name" autocomplete="off" value="<?php echo $this->result["name"]; ?>" placeholder="Ingrese su Nombre">
            </div>
            <div class="form-group col-sm-6">
                <label>Apellido *</label>
                <input type="text" class="form-control" id="last" name="last" autocomplete="off" value="<?php echo $this->result["last"]; ?>" placeholder="Ingrese su Apellido">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Tipo de Documento *</label>
                <select class="form-control" id="type_document" name="type_document">
                    <?php foreach ($this->type_document as $td_id => $td): ?>
                        <option value="<?php echo $td_id; ?>" <?php echo ($td_id == $this->result["type_document"]) ? "selected='selected'" : ""; ?>><?php echo utf8_encode($td); ?></option>                       <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group col-sm-6">
                <label>Número *</label>
                <input type="text" class="form-control" id="number" name="number" autocomplete="off" value="<?php echo $this->result["number"]; ?>" placeholder="Número">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-12">
                <label>E-Mail *</label>
                <input type="text" class="form-control" id="email" name="email" autocomplete="off" value="<?php echo $this->result["email"]; ?>" placeholder="Ingrese su E-Mail">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-12">
                <input type="checkbox" value="1" name="accept" id="accept">
                He leido y estoy de acuerdo con los <a href="javascript:abrir ('<?php echo $this->setting["eidicom"]["siteurl"] ?>contents_pop.php?show=terms','400','960','centro');">Términos y Condiciones</a>
            </div>
        </div>
        <div class="text-center" id="loading" style="display: none;">
            <img src='<?php echo $this->baseUrl(); ?>/imgs/loading.gif'><br/>
        </div>
        <div class="text-center">
            <button type="button" id="submit" onclick="register();" class="btn btn-primary">Registrarse</button>
        </div>
    </div>
    <script>
        $('#email').keyup(function(e) {
            if (e.keyCode == 13)
            {
                register();
            }
        });
        function lockSubmit(lock) {
            if (lock == true) {
                $("#loading").fadeIn("fast");
                $("#submit").removeClass("btn-primary").addClass("btn-default").addClass("disabled").html("Validando sus datos, por favor espere...").blur();
            } else {
                $("#loading").fadeOut("fast");
                $("#submit").addClass("btn-primary").removeClass("btn-default").removeClass("disabled").html("Registrarse");
            }
        }
        function register() {
            $(".alert.alert-danger").slideUp('fast');
            $(".alert.alert-success").slideUp('fast');
            lockSubmit(true);
            accept=0;
            if ($('#accept').is(':checked')) {
                accept=1;
            }
            $.post("<?php echo $this->url(array('controller' => 'login', 'action' => 'register')); ?>",
                    {
                        token: "<?php echo $this->token ?>",
                        name: $("#name").val(),
                        fox_id: $("#fox_id").val(),
                        last: $("#last").val(),
                        type_document: $("#type_document").val(),
                        number: $("#number").val(),
                        email: $("#email").val(),
                        accept: accept,
                    })
                    .done(function(data) {
                        if (data.length > 0) {
                            result = jQuery.parseJSON(data);
                            if (result.response == false) {
                                lockSubmit(false);
                                $(".alert.alert-danger").slideDown('fast', function(index) {
                                    $(".alert.alert-danger").html(result.message);
                                });
                            } else {
                                $(".alert.alert-success").slideDown('fast', function(index) {
                                    $(".alert.alert-success").html(result.message);
                                    if (result.goback == "" || result.goback == "null" || result.goback == null || result.goback == undefined) {
                                        location.reload();
                                    } else {
                                        location.href = result.goback;
                                    }
                                });
                            }
                        }
                    });
        }
    </script>