<?php if ($this->parameters["popup"] == false) : ?>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">Inicio</a></li>
        <li class="active">Regístrate</li>
    </ol>
<?php endif; ?>
<?php if ($this->response) { ?>
    <p class="text-danger text-center"><?php echo $this->response ?></p>
<?php } ?>
<?php if ($this->parameters["popup"] == true): ?>
    <div class="col-xs-12">
    <?php else: ?>
        <div class="col-lg-4 col-lg-offset-4 col-xs-12">
        <?php endif; ?>
        <div class="alert alert-danger" style="display: none;"></div>
        <div class="alert alert-success" style="display: none;"></div>
        <p>Ingresá tu Tipo y Número de Documento</p>
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Tipo de Documento *</label>
                <select class="form-control" id="type_document" name="type_document">
                    <?php foreach ($this->type_document as $td_id => $td): ?>
                        <option value="<?php echo $td_id; ?>" <?php echo ($td_id == 32) ? "selected='selected'" : ""; ?>><?php echo utf8_encode($td); ?></option>                       <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group col-sm-6">
                <label>Número *</label>
                <input type="text" class="form-control keyenter" id="number" name="number" autocomplete="off" value="" placeholder="Número">
            </div>
        </div>
        <br/>
        <div class="text-center" id="loading" style="display: none;">
            <img src='<?php echo $this->baseUrl(); ?>/imgs/loading.gif'><br/>
        </div>
        <div class="text-center">
            <button type="button" id="submit" onclick="search();" class="btn btn-primary">Buscar</button>
        </div>
        <div class="text-center" id="no_result" style="display:none;" >
            <br/>
            <p><a href="javascript:openModalScript('ajax', '<b>Registrate en EIDICOM</b>', '', '<?php echo $this->url(array('action'=>'register'));?>', '500px', '300px');">Registrate</a></p>
        </div>
    </div>
    <script>
        var textDefault = "Buscar";
        $('.keyenter').keyup(function(e) {
            if (e.keyCode == 13)
            {
                search();
            }
        });
        function lockSubmit(lock) {
            if (lock == true) {
                $("#loading").fadeIn("fast");
                $("#submit").removeClass("btn-primary").addClass("btn-default").addClass("disabled").html("Buscando, por favor espere...").blur();
            } else {
                $("#loading").fadeOut("fast");
                $("#submit").addClass("btn-primary").removeClass("btn-default").removeClass("disabled").html(textDefault);
            }
        }
        function search() {
            $(".alert.alert-danger").slideUp('fast');
            $(".alert.alert-success").slideUp('fast');
            lockSubmit(true);
            $.post("<?php echo $this->url(array('controller' => 'login', 'action' => 'search')); ?>",
                    {
                        token: "<?php echo $this->token ?>",
                        type_document: $("#type_document").val(),
                        number: $("#number").val(),
                    })
                    .done(function(data) {
                        if (data.length > 0) {
                            result = jQuery.parseJSON(data);
                            if (result.response == false) {
                                lockSubmit(false);
                                $(".alert.alert-danger").slideDown('fast', function(index) {
                                    $(".alert.alert-danger").html(result.message);
                                });
                            } else {
                                if (result.goback == "" || result.goback == "null" || result.goback == null || result.goback == undefined) {
                                    textDefault = "Volver a buscar";
                                    lockSubmit(false);
                                    $(".alert.alert-danger").slideDown('fast', function(index) {
                                        $(".alert.alert-danger").html(result.message);
                                    });
                                    $("#no_result").fadeIn("fast");
                                } else {
                                    $(".alert.alert-success").slideDown('fast', function(index) {
                                        $(".alert.alert-success").html(result.message);
                                        openModalScript('ajax', '<b>Registrate en EIDICOM</b>', '', result.goback, '500px', '300px');
                                    });
                                }
                            }
                        }
                    });
        }
    </script>