<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="./assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        SmartPro
    </title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css" integrity="sha512-apX8rFN/KxJW8rniQbkvzrshQ3KvyEH+4szT3Sno5svdr6E/CP0QE862yEeLBMUnCqLko8QaugGkzvWS7uNfFQ==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/imgs/favicon.png'))
            ->prependStylesheet($this->baseUrl() . '/fe/assets/css/material-kit.css?v=2.0.7')
            ->prependStylesheet($this->baseUrl() . '/toast-master/css/jquery.toast.css')
            ->prependStylesheet($this->baseUrl() . '/css/loading.css')
            ->prependStylesheet($this->baseUrl() . '/fe/assets/demo/demo.css');
    ?>
    <script>
    function after401(){ return; }
    function after200(){ return; }
    function after404(){ return; }
    function after500(){ errorGeneral() }
    </script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/core/popper.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/plugins/moment.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/material-kit.js?v=2.0.7" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl();?>/toast-master/js/jquery.toast.js"></script>
    <script src="<?php echo $this->baseUrl();?>/fe/assets/js/es.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js"></script> 
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script> 
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script> 
    
    <script>
        $(document).ready(function() {
            materialKit.initFormExtendedDatetimepickers();
            materialKit.initSliders();
            $( "form.sendToApi" ).ajaxForm({
                dataType:'json',
                beforeSubmit: beforeSubmit
            });
            $("a.preloading").on('click',function(){
                loading.show();
            })
        });
        function scrollToDownload() {
            if ($('.section-download').length != 0) {
                $("html, body").animate({
                    scrollTop: $('.section-download').offset().top
                }, 1000);
            }
        }
        var loading={
            show: function (){
                $("div.loading").fadeIn();
                return true;
            },
            hide: function (){
                $("div.loading").fadeOut();
                return true;
            }
        }
        var options = {
            dataType:'json',
            beforeSubmit: beforeSubmit
        };
        
        function beforeSubmit(formData, form, options) {
            loading.show();
            form.closest('form').find(':submit').attr('disabled',true);
            var inputs=form.closest('form').find(':input:not(.dropify)');
            inputs.parent().removeClass('has-danger');
            inputs.next('small').html('');

            var data=preRequest();
            for (var i = formData.length - 1; i >= 0; i--) {
                data[formData[i].name]=formData[i].value;
            }
            $.ajax({
                url: form.attr("action"),
                type: ($('input[name="_method"]').length>0)?$('input[name="_method"]').val():form.attr("method").toUpperCase(),
                data:JSON.stringify(data),
                contentType: "application/json",
                crossDomain: true,
                success: function(data) {
                    after200(data);
                },  
                complete:function(){
                    form.closest('form').find(':submit').attr('disabled',false);
                },
                error: function(data, status, error) {
                    loading.hide();
                    if(data.status==400){
                        after400(JSON.parse(data.responseText));
                    }else if(data.status == 404){
                        after404();
                    }else if(data.status == 403){
                        after403();
                    }else if(data.status == 500){
                        after500();
                    }
                }
            });
            return false;
        }
        function preRequest(){ return {}}
        function after400(data){ 
            var text='';
            for(i=0; i<data.data.length; i++){
                const item=data.data[i];
                text+=item.message+'<br/>';
                input=$("#"+item.property);
                //input.parent().addClass('has-danger');
                input.after('<small class="text-danger">'+item.message+'</small>');
                //input.addClass("is-invalid");
            }
            $.toast({
                heading: 'UPS!',
                text: 'Ocurrió un error',
                position: 'top-right',
                icon: 'error',
                hideAfter: 3000, 
                stack: 6
            });
            return; 
        }
        
        function errorGeneral(){
            $.toast({
                heading: 'UPS!',
                text: 'Ocurrió un error, intente en otro momento',
                position: 'top-right',
                icon: 'error',
                hideAfter: 3000, 
                stack: 6
            });
        }

        function logout(){
            loading.show();
            $.ajax({
                url: '<?php echo $this->url(['module'=>'api','controller'=>'productors','action'=>'logout'])?>',
                crossDomain: true,
                success: function(data) {
                    location.href='<?php echo $this->url(['module'=>'default','controller'=>'login'],null,true)?>'
                },  
                complete:function(){},
                error: function(data, status, error) {}
            });
        }
    </script>
<body>
    <div class="loading">
        <div class='uil-ring-css' style='transform:scale(0.79);'>
            <div></div>
        </div>
    </div>
    <?php if($this->parameters['controller']!='login') :?>
        <?php echo $this->render('navbar.phtml'); ?>
        <?php echo $this->render('page-header.phtml'); ?>
    <?php endif;?>
    <?php if($this->parameters['controller']!='login') :?>
        <div class="main main-raised">
    <?php endif;?>
        <?php echo $this->layout()->content; ?>
    <?php if($this->parameters['controller']!='login') :?>
        </div>
    <?php endif;?>
    <?php if($this->parameters['controller']!='login') :?>
        <?php echo $this->render('footer.phtml'); ?>
    <?php endif;?>
    <script>
    $(function (){
        loading.hide();
        $('.datetimepicker').datetimepicker({
            format:'DD/MM/YYYY',
            locale:'es',
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
        });
    })
    </script>
</body>

</html>