<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="Description" content="Web development at Dot where creativity meets technology" />
        <meta content="IE=edge" http-equiv="X-UA-Compatible" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
        <meta name="format-detection" content="telephone=no" />
        <meta name="robots" content="index,follow" />
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/imgs/favicon.png'))
                ->prependStylesheet($this->baseUrl() . '/css/404.css')
                ->prependStylesheet($this->baseUrl() . '/css/base.css');
        echo $this->headScript()->prependFile($this->baseUrl() . '/js/independent/modernizr.custom.js', 'text/javascript');
        ?>
        <link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <?php
        echo $this->layout()->content;
        ?>
    </body>
</html>