<?php echo $this->render('_alert.phtml'); ?>
<ol class="breadcrumb hidden-print">
    <li><a href="<?php echo $this->url(array('controller' => 'sinister', 'action' => 'index'), NULL, TRUE); ?>">Noticias</a></li>
    <li class="active"><?php echo $this->new["ne_title"]; ?></li>
</ol>
<div class="row">
    <div class="col-md-6">
        <img src="<?php echo HOST . $this->baseUrl() . URL_IMG . $this->new["ne_picture"]; ?>" class="full-width"> 
    </div>
    <div class="col-md-6">
        <h1 class="text-primary" style="margin-top: 0;"><?php echo $this->new["ne_title"]; ?></h1>
        <?php echo ($this->new["ne_subtitle"]) ? "<h3 class='text-primary'>" . $this->new["ne_subtitle"] . "</h3>" : ""; ?>
        <p>
            <?php echo $this->new["ne_content"]; ?>
        </p>
    </div>
</div>