<div class="form-container" >
    <blockquote class="hidden-print">
        <?php if ($this->title) { ?>
        <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
        <small class="visible-lg visible-md visible-sm"><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="form" method="post" novalidate enctype="multipart/form-data">

        <input type="hidden" name="token" value="<?php echo $this->token; ?>">
        <!--<div class="row hidden-print">-->
            <?php
            if ($this->partial):
                echo '<div class="clearfix"></div>';
                echo $this->render($this->partial);
            endif;
            $c = 0;
            foreach ($this->fields as $key => $field):
                $c++;
                if ($key == 0 || $field["notdisplay"] == true)
                    continue;
                switch ($field["type"]):
                case "image":
                echo '<div class="clearfix"></div>';
                ?>
                <div class="form-group col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?>
                        </div>
                        <div class="panel-body">
                            <div class="col-xs-6">
                                <label>Vista Previa</label>
                                <br/>
                                <?php if (!empty($this->result[$this->fields[$key]["field"]]) && file_exists(PATH_IMG . $this->result[$this->fields[$key]["field"]])): ?>
                                    <img class="thumbnail" style="max-width:100%;" src="<?php echo $this->baseUrl() . URL_IMG . $this->result[$this->fields[$key]["field"]]; ?>"/>
                                <?php else: ?>
                                    <img class="thumbnail" width="100%" data-src="holder.js/<?php echo $this->fields[$key]["x"] ?>x<?php echo $this->fields[$key]["y"] ?>?auto=yes">
                                <?php endif; ?>
                            </div>
                            <div class="col-xs-6">
                                <label>Reemplazar</label>
                                <br/>
                                <input <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> type="file" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control">
                                <div class="checkbox">
                                    <label>
                                        <input <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> <?php if (empty($this->result[$this->fields[$key]["field"]]) || !file_exists(PATH_IMG . $this->result[$this->fields[$key]["field"]])): ?> disabled="disabled" checked="checked" <?php endif; ?> type="checkbox" name="remove_<?php echo $this->fields[$key]["field"] ?>" value="1"> Quitar
                                    </label>
                                </div>
                                <div class="checkbox">
                                    Tamaño recomendado: <?php echo $this->fields[$key]["x"] ?>x<?php echo $this->fields[$key]["y"] ?> px 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <?php
                break;
                case "gallery":
                echo '<div class="clearfix"></div>';
                ?>
                
                <!-- <br>
                <div id="progress" class="progress">
                    <div class="progress-bar progress-bar-success"></div>
                </div>
                <div id="files" class="files"></div> -->
                
                <script>
                    window.onload = function() {
                        document.getElementById("pasteTarget").
                        addEventListener("paste", handlePaste);
                    }
                    function checkURL(url) {
                        return(url.match(/\.(jpeg|jpg|gif|png)$/) != null);
                    }
                    function handlePaste(e) {
                        // console.log(e.clipboardData.getData('Text'));
                        console.log(e.clipboardData);
                        subir(e.clipboardData.getData('Text'));
                       
                    }
                    function subir(url){
                        if(checkURL(url)){
                            $('#pleaseWaitDialog').modal('show');
                            $.post("<?php echo $this->url(array('module'=>'admin','controller'=>'gallery','action'=>'uploadbyurl')) ?>",
                            {
                                url: url,
                            })
                            .done(function(data) {
                                data=JSON.parse(data);
                                returnGallery('<?php echo $this->fields[$key]["field"] ?>',data.file,data.file);
                            })
                            .always(function(){
                                $('#pleaseWaitDialog').modal('hide');
                            });
                        }
                    }
                    $(function () {

                        'use strict';
                        $('#fileupload').fileupload({
                            url: '<?php echo $this->url(array('module'=>'admin','controller'=>'gallery','action'=>'uploadbyajax')) ?>',
                            dataType: 'json',
                            done: function (e, data) {
                                returnGallery('<?php echo $this->fields[$key]["field"] ?>',data.result.file,data.result.file);
                                $('#pleaseWaitDialog').modal('hide');
                            },
                            error: function(err){
                                // console.log(err);
                                $('#pleaseWaitDialog').modal('hide');
                            },
                            progressall: function (e, data) {
                                $('#pleaseWaitDialog').modal('show');
                                var progress = parseInt(data.loaded / data.total * 100, 10);
                                console.log(progress);
                                $('#progress .progress-bar').css(
                                    'width',
                                    progress + '%'
                                    );
                            }
                        }).prop('disabled', !$.support.fileInput)
                        .parent().addClass($.support.fileInput ? undefined : 'disabled');
                    });
                </script>
                <div class="form-group col-lg-12" >
                    <div class="row">
                        <div class="panel panel-default" id="pasteTarget">
                            <div class="panel-heading">
                                <?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?>
                                <?php if ($this->formDisabled != true): ?>
                                    <!-- <button type="button" onclick="openModalScript('iframe', '<b>Agregar Foto o Video</b>', '', '<?php
                                        echo $this->url(array(
                                            'module' => 'admin',
                                            'controller' => 'gallery',
                                            'action' => 'upload',
                                            'popup' => true,
                                            'resize' => $field["resize"],
                                            'cut' => $field["cut"],
                                            'field' => $this->fields[$key]["field"]
                                        ), null, true);
                                        ?>', '1024px', '700px');" class="btn btn-sm btn-success pull-right">Agregar Foto</button> -->
                                        <span class="btn btn-success fileinput-button pull-right">
                                            <i class="glyphicon glyphicon-plus"></i>
                                            <span>Seleccionar archivos</span>
                                            <input id="fileupload" type="file" name="files[]" multiple>
                                        </span>
                                        <div class="clearfix"></div>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" id="<?php echo $this->fields[$key]["field"] ?>">
                                    <blockquote class="hidden-print">
                                        <p class="text-primary">Arrastre y suelte aquí las imágenes o haga click en '+ Seleccionar archivos'</p>
                                        <small class="visible-lg visible-md visible-sm">Recuerde que puede copiar la url de una imagen de internet y presionar Crtl + v para subirla.</small>
                                    </blockquote>
                                    <?php
                                    if ($this->fields[$key]["data"]):
                                        foreach ($this->fields[$key]["data"] as $item):
                                            if ($item["ga_type"] == 'photo'):
                                                ?>
                                                <div class='col-lg-3 col-md-4 col-sm-6 col-xs-12 hidden-print remove' id='<?php echo $item["ga_id"] ?>'>
                                                    <img class='thumbnail' style='max-width:100%;' src='<?php echo $this->baseUrl() . URL_IMG . "s/" . $item["ga_name"]; ?>'/>
                                                    <?php if ($this->formDisabled != true): ?>
                                                        <button class="btn btn-xs btn-danger" onclick='removeDiv("<?php echo $item["ga_id"] ?>")'>
                                                            <span class='glyphicon glyphicon-trash'></span> Quitar
                                                        </button>
                                                        <input type='hidden' name='<?php echo $this->fields[$key]["field"] ?>[]' value='<?php echo $item["ga_name"] ?>'>
                                                        <input type='hidden' name='type_<?php echo $this->fields[$key]["field"] ?>[]' value='<?php echo $item["ga_type"] ?>'>
                                                    <?php endif; ?>
                                                </div>
                                                <div class='col-xs-4 visible-print' id='<?php echo $item["ga_id"] ?>'>
                                                    <img style='max-width:100%;' src='<?php echo $this->baseUrl() . URL_IMG . "s/" . $item["ga_name"]; ?>'/>
                                                </div>
                                                <?php
                                            elseif ($item["ga_type"] == 'video'):
                                                ?>
                                                <div class='col-lg-3 col-md-4 col-sm-6 col-xs-12 remove' id='<?php echo $item["ga_id"] ?>'>
                                                    <iframe class='thumbnail' width='100%' src='<?php echo $item["ga_name"] ?>' frameborder='0' allowfullscreen></iframe>
                                                    <?php if ($this->formDisabled != true): ?>
                                                        <button class="btn btn-xs btn-danger" onclick='removeDiv("<?php echo $item["ga_id"] ?>")'>
                                                            <span class='glyphicon glyphicon-trash'></span> Quitar
                                                        </button>
                                                        <input type='hidden' name='<?php echo $this->fields[$key]["field"] ?>[]' value='<?php echo $item["ga_name"] ?>'>
                                                        <input type='hidden' name='type_<?php echo $this->fields[$key]["field"] ?>[]' value='<?php echo $item["ga_type"] ?>'>
                                                    <?php endif; ?>
                                                </div>
                                                <?php
                                            endif;
                                        endforeach;
                                    endif;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <?php
                    break;
                    case "partial-view":
                    echo '<div class="clearfix"></div>';
                    echo $this->render($this->fields[$key]["file"]);

                    break;
                    case "divider":
                    echo '<div class="clearfix"></div>';

                    break;
                    case "checkbox":
                    ?>
                    <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                        <div class="checkbox" >
                            <label >
                                <input type="checkbox" <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> <?php echo ($this->result[$this->fields[$key]["field"]] == 1) ? "checked='checked'" : ""; ?> name="<?php echo $this->fields[$key]["field"] ?>" value="1"> <b><?php echo $this->fields[$key]["label"] ?></b>
                            </label>
                        </div>
                    </div>
                    <?php
                    break;
                    case "combo":
                    ?>
                    <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                        <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                        <select <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> class="form-control"  id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?> >
                            <?php if (!empty($field["option-empy"])): ?>
                                <option value=""><?php echo $field["option-empy"] ?></option>
                            <?php endif; ?>
                            <?php foreach ($this->fields[$key]["data"] as $index => $value): ?>
                                <option <?php echo ($this->result[$this->fields[$key]["field"]] == $index) ? 'selected="selected"' : ''; ?> value="<?php echo $index ?>"><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <?php
                    break;
                    case "textarea":
                    ?>
                    <div class="form-group col-xs-12 hidden-print">
                        <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                        <textarea <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?>
                            name="<?php echo $this->fields[$key]["field"] ?>" class="form-control <?php echo ($field["html"] == true) ? "rta" : ""; ?>" 
                            placeholder="<?php echo $this->fields[$key]["label"] ?>"  <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>
                            ><?php echo $this->result[$this->fields[$key]["field"]] ?></textarea>
                        </div>
                        <div class="form-group col-xs-12 visible-print">
                            <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                            <textarea <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?>
                                class="form-control <?php echo ($field["html"] == true) ? "rta" : ""; ?>" 
                                placeholder="<?php echo $this->fields[$key]["label"] ?>"  <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>
                                style="resize: none; height: 100px;"><?php echo $this->result[$this->fields[$key]["field"]] ?></textarea>
                            </div>
                            <?php
                            break;
                            case "password":
                            ?>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="" type="password" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                                placeholder="<?php echo $this->fields[$key]["label"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            case "hidden":
                            ?>
                            <input <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                            value="<?php echo $this->result[$this->fields[$key]["field"]] ?>" type="hidden" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                            placeholder="<?php echo $this->fields[$key]["label"] ?>" <?php // echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : "";                       ?>>

                            <?php
                            break;

                            case "file":
                            ?>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo $this->fields[$key]["attr"] ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="" type="file" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                                <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            case "money":
                            ?>
                            <div class="form-group col-lg-2 col-md-3 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo $this->fields[$key]["attr"] ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="<?php echo $this->result[$this->fields[$key]["field"]] ?>" type="text" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                                placeholder="$ <?php echo $this->fields[$key]["label"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            case "number":
                            ?>
                            <div class="form-group col-lg-2 col-md-3 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo $this->fields[$key]["attr"] ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="<?php echo $this->result[$this->fields[$key]["field"]] ?>" type="number" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                                placeholder="<?php echo $this->fields[$key]["label"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            case "date":
                            ?>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo $this->fields[$key]["attr"] ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="<?php echo ($this->result[$this->fields[$key]["field"]] != "0000-00-00" && $this->result[$this->fields[$key]["field"]] != "") ? date("d/m/Y", strtotime($this->result[$this->fields[$key]["field"]])) : date("d/m/Y"); ?>" type="text" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" 
                                <?php if ($field["calendar"] == true): ?>
                                    class="calendar form-control" readonly="readonly"
                                <?php else: ?>
                                    class="form-control"
                                <?php endif; ?>
                                placeholder="<?php echo $this->fields[$key]["label"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            case "panel_start":
                            ?>
                            <div class="col-xs-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><?php echo $this->fields[$key]["label"] ?></div>
                                    <div class="panel-body row">
                                        <?php
                                        break;
                                        case "panel_end":
                                        ?>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                            <?php
                            break;
                            default:
                            ?>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                                <label for="<?php echo $this->fields[$key]["field"] ?>"><?php echo $this->fields[$key]["label"] ?> <?php echo ($this->fields[$key]["required"]) ? "*" : ""; ?></label>
                                <input <?php echo ($this->fields[$key]["attr"]) ? $this->fields[$key]["attr"] : ""; ?> <?php echo $this->fields[$key]["attr"] ?> <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> 
                                value="<?php echo $this->result[$this->fields[$key]["field"]] ?>" type="text" id="<?php echo $this->fields[$key]["field"] ?>" name="<?php echo $this->fields[$key]["field"] ?>" class="form-control" 
                                placeholder="<?php echo $this->fields[$key]["label"] ?>" <?php echo ($this->fields[$key]["required"]) ? 'data-validate="' . $this->fields[$key]["required"] . '"' : ""; ?>>
                            </div>
                            <?php
                            break;
                            endswitch;
                            if (count($this->fields) <= $c):
                                echo '<div class="clearfix"></div>';
                            endif;
                        endforeach;
                        ?>
                        <!--</div>-->
                        <div class="btn-group hidden-print">
                            <?php if ($this->parameters["action"] == "detail") { ?>
                            <button type="button" class="btn btn-info" onclick="location.href = '<?php echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'edit', 'id' => $this->result[$this->fields[0]["field"]]), '', true) ?>'" >Editar</button>
                            <?php } elseif ($this->formDisabled) { ?>
                            <button type="button" class="btn btn-default" onclick='location.href = "<?php echo $this->url(array('module' => $this->parameters["module"], 'controller' => $this->parameters["controller"], 'action' => 'index'), null, true) ?>"'>Volver</button>
                            <?php } else { ?>
                            <button type="submit" name="submit" class="btn btn-info" data-loading-text="Validando...">Guardar</button>
                            <button type="button" class="btn btn-default" onclick='location.href = "<?php echo $this->url(array('module' => $this->parameters["module"], 'controller' => $this->parameters["controller"], 'action' => 'index'), null, true) ?>"'>Cancelar</button>
                            <?php } ?>
                        </div>
                    </form>
                </div>
                <script>
                    $(function() {
    //       $(".form-control").first().focus(); 
});
                    function returnGallery(field, image, url) {
                        console.log(field,image,url);
                        date = new Date();
                        id = date.getTime();
                        if (image != "" && image != undefined) {
                            $("#" + field).append("<div class='col-lg-3 col-md-4 col-sm-6 col-xs-12 remove' id='" + id + "'>\n\
                                <img class='thumbnail' style='max-width:100%;' src='<?php echo $this->baseUrl() . URL_IMG; ?>" + image + "'/>\n\
                                <button class='btn btn-xs btn-danger' onclick='removeDiv(" + id + ")'><span class='glyphicon glyphicon-trash'></span> Quitar</button>\n\
                                <input type='hidden' name='" + field + "[]' value='" + image + "'>\n\
                                <input type='hidden' name='type_" + field + "[]' value='photo'>\n\
                                </div>");
                        } else if (url != "" && url != undefined) {
                            $("#" + field).append("<div class='col-lg-3 col-md-4 col-sm-6 col-xs-12 remove' id='" + id + "'>\n\
                                <iframe class='thumbnail' width='100%' src='" + url + "' frameborder='0' allowfullscreen></iframe>\n\
                                <button class='btn btn-xs btn-danger' onclick='removeDiv(" + id + ")'><span class='glyphicon glyphicon-trash'></span> Quitar</button>\n\
                                <input type='hidden' name='" + field + "[]' value='" + url + "'>\n\
                                <input type='hidden' name='type_" + field + "[]' value='video'>\n\
                                </div>");
                        }
                    }
                    <?php if ($this->parameters["action"] != "detail") { ?>
                        $(function() {
                            var count = 0;
                            $(".sortable").sortable({
                                stop: function(event, ui) {
                                }
                            });
                            $(".sortable").disableSelection();
                        });
                        <?php } ?>
                    </script>