<ul class="nav" id="side-menu">
    <?php if (!@in_array('index', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("index" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-dashboard fa-fw"></i> Dashboard
            </a>
        </li>
    <?php endif; ?>

    <?php if (!@in_array('sinister', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("sinister" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'sinister', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-star fa-fw"></i> Siniestros
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('customer', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("customer" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'customer', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-user fa-fw"></i> Clientes
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('company', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("company" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'company', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-unlock-alt fa-fw"></i> Compañías Aseguradoras
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('productors', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("productors" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'productors', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-users fa-fw"></i> Productores de seguro
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('transport', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("transport" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'transport', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-truck fa-fw"></i> Transportes
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('provider', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("provider" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'provider', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-life-ring fa-fw"></i> Proveedores
            </a>
        </li>
    <?php endif; ?>
    <?php if (!@in_array('accesory', $this->loginInfo["accessRestring"]["controllers"])): ?>
        <li>
            <a <?php echo("accesory" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'accesory', 'action' => 'index'), '', true); ?>">
                <i class="fa fa-barcode fa-fw"></i> Productos
            </a>
        </li>
    <?php endif; ?>
    <?php /*
    <li <?php 
    echo("branch" == $this->parameters["controller"] ||
    "model" == $this->parameters["controller"]) ? "class='active'" : "";
    ?>>
        <a href="#"><i class="fa fa-car fa-fw"></i></i> Vehículos<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <?php if (!@in_array('branch', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("branch" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'branch', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Marcas
                    </a>
                </li>
            <?php endif; ?>
            <?php if (!@in_array('model', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("model" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'model', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Modelos
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>   
    <?php */ ?>
    <?php /* 
    <li <?php
    echo(
    "tbranch" == $this->parameters["controller"] ||
    "tmodel" == $this->parameters["controller"] ||
    "bbranch" == $this->parameters["controller"] ||
    "bmodel" == $this->parameters["controller"] ||
    "tsize" == $this->parameters["controller"] ||
    "cbranch" == $this->parameters["controller"] ||
    "accesory" == $this->parameters["controller"] ||
    "cmodel" == $this->parameters["controller"]
    ) ? "class='active'" : "";
    ?>>
        <a href="#"><i class="fa fa-wrench fa-fw"></i>Repuestos<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <?php if (!@in_array('tbranch', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("tbranch" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'tbranch', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Llantas
                    </a>
                </li>
            <?php endif; ?>
            <?php if (!@in_array('cbranch', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("cbranch" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cbranch', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Neumáticos
                    </a>
                </li>
            <?php endif; ?>
            <?php if (!@in_array('bbranch', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("bbranch" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'bbranch', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Baterías
                    </a>
                </li>
            <?php endif; ?>
            <?php if (!@in_array('accesory', $this->loginInfo["accessRestring"]["controllers"])): ?>
                <li>
                    <a <?php echo("accesory" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'accesory', 'action' => 'index'), '', true); ?>">
                        <i class="fa fa-asterisk"></i> Accesorios / Servicios
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
    <?php
    */
    if (
            !@in_array('maintenance', $this->loginInfo["accessRestring"]["controllers"]) ||
            !@in_array('user', $this->loginInfo["accessRestring"]["controllers"]) ||
            !@in_array('roles', $this->loginInfo["accessRestring"]["controllers"]) ||
            !@in_array('stats', $this->loginInfo["accessRestring"]["controllers"]) ||
            !@in_array('setting', $this->loginInfo["accessRestring"]["controllers"])
    ):
        ?>
        <li <?php
        echo("maintenance" == $this->parameters["controller"] ||
        "user" == $this->parameters["controller"] ||
        "stats" == $this->parameters["controller"] ||
        "roles" == $this->parameters["controller"] ||
        "setting" == $this->parameters["controller"]) ? "class='active'" : "";
        ?>>
            <a href="#"><i class="fa fa-gears fa-fw"></i></i> Configuración<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
                <?php if (!@in_array('stats', $this->loginInfo["accessRestring"]["controllers"])): ?>
                    <li>
                        <a <?php echo("stats" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'stats', 'action' => 'index'), '', true); ?>">
                            <i class="fa fa-line-chart fa-fw"></i> Reportes
                        </a>
                    </li>
                <?php endif; ?>
                <?php if (!@in_array('roles', $this->loginInfo["accessRestring"]["controllers"])): ?>
                    <li>
                        <a <?php echo("roles" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'roles', 'action' => 'index'), '', true); ?>">
                            <i class="fa fa-sitemap fa-fw"></i> Roles de Administradores
                        </a>
                    </li>
                <?php endif; ?>
                <?php if (!@in_array('user', $this->loginInfo["accessRestring"]["controllers"])): ?>
                    <li>
                        <a <?php echo("user" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'index'), '', true); ?>">
                            <i class="fa fa-users fa-fw"></i> Administradores
                        </a>
                    </li>
                <?php endif; ?>
                <?php if (!@in_array('setting', $this->loginInfo["accessRestring"]["controllers"])): ?>
                    <li>
                        <a <?php echo("setting" == $this->parameters["controller"]) ? "class='active'" : ""; ?> href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'setting', 'action' => 'detail', 'id' => 1), '', true); ?>">
                            <i class="fa fa-globe fa-fw"></i> General
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
            <!-- /.nav-second-level -->
        </li>
    <?php endif; ?>  
    <li class="visible-xs">
        <a href="#"><i class="fa fa-user fa-fw"></i></i> Mi Cuenta<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => $this->loginInfo["IDUser"]), '', true); ?>">
                    <i class="fa fa-edit fa-fw"></i> Mi Perfil
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'login', 'action' => 'logout'), '', true); ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.nav-second-level -->
    </li>
</ul>