<?php if ($this->parameters["popup"] == false) : ?>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">Inicio</a></li>
        <li class="active">Iniciar Sesi&oacute;n</li>
    </ol>
<?php endif; ?>
<?php if ($this->response) { ?>
    <p class="text-danger text-center"><?php echo $this->response ?></p>
<?php } ?>
<?php if ($this->parameters["popup"] == true): ?>
    <div class="col-xs-12">
    <?php else: ?>
        <div class="col-lg-4 col-lg-offset-4 col-xs-12">
        <?php endif; ?>
        <div class="alert alert-danger" style="display: none;"></div>
        <div class="alert alert-success" style="display: none;"></div>
            <div class="form-group">
                <label>Ingresa tu E-mail para enviarte la nueva clave</label>
                <input type="text" class="form-control" id="email" name="email" autocomplete="on" value="<?php echo $this->parameters["email"] ?>" placeholder="Su E-Mail">
            </div>
            <div class="text-center" id="loading" style="display: none;">
                <img src='<?php echo $this->baseUrl(); ?>/imgs/loading.gif'><br/>
            </div>
            <div class="text-center btn-group">
                <button type="button" class="btn btn-default" onclick="closeModal();">Cancelar</button>
                <button type="button" id="submit" onclick="login();" class="btn btn-primary">Recuperar Clave</button>
            </div>
        
    </div>
    <script>
        function lockSubmit(lock) {
            if (lock == true) {
                $("#loading").fadeIn("fast");
                $("#submit").removeClass("btn-primary").addClass("btn-default").addClass("disabled").html("Por favor espere...").blur();
            } else {
                $("#loading").fadeOut("fast");
                $("#submit").addClass("btn-primary").removeClass("btn-default").removeClass("disabled").html("Recuperar Clave");
            }
        }
        
        $('#password').keyup(function(e) {
            if (e.keyCode == 13)
            {
                login();
            }
        });
        function login() {
            $(".alert.alert-danger").slideUp('fast');
            $(".alert.alert-success").slideUp('fast');
            lockSubmit(true);
            $.post("<?php echo $this->url(array('controller' => 'login', 'action' => 'forgotpassword')); ?>",
                    {
                        token: "<?php echo $this->token ?>",
                        email: $("#email").val(),
                    })
                    .done(function(data) {

//                        alert(data);
                        if (data.length > 0) {
                            result = jQuery.parseJSON(data);
                            if (result.response == false) {
                                lockSubmit(false);
                                $(".alert.alert-danger").slideDown('fast', function(index) {
                                    $(".alert.alert-danger").html(result.message);
                                });
                            } else {
                                $(".alert.alert-success").slideDown('fast', function(index) {
                                    $(".alert.alert-success").html(result.message);
                                    if (result.goback == "" || result.goback == "null" || result.goback == null || result.goback == undefined) {
                                        location.reload();
                                    } else {
                                        location.href = result.goback;
                                    }
                                });
                            }
                        }
                    });
            $("#password").val("");
        }
    </script>