<div class="login-page sidebar-collapse">
    <div class="page-header-login header-filter" style="background-image: url('<?php echo $this->baseUrl();?>/fe/assets/img/bg7.jpg'); background-size: cover; background-position: top center;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 ml-auto mr-auto">
                    <div class="card card-login">
                        <form class="form sendToApi" method="POST" action="<?php echo $this->url(['module'=>'api','controller'=>'productors','action'=>'login'])?>" novalidate>
                            <div class="card-header card-header-primary text-center p-0">
                                <img src="<?php echo $this->baseUrl()."/fe/assets/img/logo-smartpro-1.png";?>" style="width:70%;">
                            </div>
                            <p class="description text-center">Ingrese sus credenciales</p>
                            <div class="card-body">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">mail</i>
                                        </span>
                                    </div>
                                    <input type="email" id="pr_email" name="pr_email" class="form-control" placeholder="Email...">
                                </div>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                    </div>
                                    <input type="password" id="pr_password" name="pr_password" class="form-control" placeholder="Contraseña...">
                                </div>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary btn-link btn-wd btn-lg" type="submit">Ingresar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function after404(){
        $.toast({
            heading: 'Login incorrecto',
            text: 'El E-Mail o la contraseña son incorrectos',
            position: 'top-right',
            icon: 'error',
            hideAfter: 3000, 
            stack: 6
        });
    }
    function after200(){
        location.href='<?php echo $this->url(['module'=>'default','controller'=>'index'],null,true)?>'
    }
</script>