<footer class="footer" data-background-color="black">
    <div class="container">
        <!-- <nav class="float-left">
            <ul>
                <li>
                    <a href="https://www.creative-tim.com/">
                        Creative Tim
                    </a>
                </li>
                <li>
                    <a href="https://www.creative-tim.com/presentation">
                        About Us
                    </a>
                </li>
                <li>
                    <a href="https://www.creative-tim.com/blog">
                        Blog
                    </a>
                </li>
                <li>
                    <a href="https://www.creative-tim.com/license">
                        Licenses
                    </a>
                </li>
            </ul>
        </nav> -->
        <div class="copyright text-center">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>, powered by <a href="http://www.apachecms.com.ar/" target="_blank">Apachecms</a>
        </div>
    </div>
</footer>