<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="<?php echo $this->url(['module'=>'default','controller'=>'index'],null,true)?>">
                <img src="<?php echo $this->baseUrl()."/fe/assets/img/logo-smartpro-1.png";?>" style="width:70%; margin-top:-35px;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <!-- <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link preloading" data-toggle="dropdown">
                        <i class="material-icons">apps</i> Components
                    </a>
                    <div class="dropdown-menu dropdown-with-icons">
                        <a href="./index.html" class="dropdown-item">
                            <i class="material-icons">layers</i> All Components
                        </a>
                        <a href="https://demos.creative-tim.com/material-kit/docs/2.0/getting-started/introduction.html" class="dropdown-item">
                            <i class="material-icons">content_paste</i> Documentation
                        </a>
                    </div>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link preloading preloading" href="<?php echo $this->url(['module'=>'default','controller'=>'index'],null,true)?>">
                        Mis siniestros
                    </a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link preloading" href="https://www.creative-tim.com/product/material-kit-pro" target="_blank">
                        <i class="material-icons">unarchive</i> Upgrade to PRO
                    </a>
                </li> -->
                <!-- <li class="nav-item">
                    <a class="nav-link preloading" rel="tooltip" title="" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank" data-original-title="Follow us on Twitter" rel="nofollow">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link preloading" rel="tooltip" title="" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank" data-original-title="Like us on Facebook" rel="nofollow">
                        <i class="fa fab fa-facebook-square"></i>
                    </a>
                </li> -->
                <!-- <li class="nav-item">
                    <a class="nav-link preloading" rel="tooltip" title="" data-placement="bottom" href="#" data-original-title="Mi perfil" rel="nofollow">
                        <i class="fa fas fa-id-badge"></i>
                    </a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link preloading" rel="tooltip" title="" data-placement="bottom" href="javascript:logout();" data-original-title="Cerrar sesión" rel="nofollow">
                        <i class="fa fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>