<div class="page-header header-filter clear-filter purple-filter" data-parallax="true" style="background-image: url('<?php echo $this->baseUrl();?>/fe/assets/img/bg2.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                <div class="brand">
                    <!-- <h3>Bienvenido a SmartPro</h3> -->
                </div>
            </div>
        </div>
    </div>
</div>