<br/>
<blockquote>
    <p class="text-primary"><label class="fa fa-line-chart"></label>Reportes</p>
</blockquote>
<hr>
<div class="row">
    <div class="col-lg-3 btn-group btn-group-lg">
        <a role="button" href="<?php echo $this->url(array('module'=>'admin','controller'=>'stats','action'=>'purchaseorder'),null,true);?>" class="btn btn-primary btn-block">
            <i class="fa fa-shopping-cart fa-5x"></i>
            <p>Orden de compra</p>
        </a>
    </div>
    <div class="col-lg-3 btn-group btn-group-lg">
        <button role="button" onclick="beforeSales('<?php echo $this->url(array('module'=>'admin','controller'=>'stats','action'=>'purchaseorder'),null,true);?>')" class="btn btn-primary btn-block">
            <i class="fa fa-usd fa-5x"></i>
            <p>Siniestros</p>
        </button>
    </div>
</div>

<script>
    var url='';
    function beforeSales(url){
        openDialog(`
        <h5>Seleccione un rago de fechas</h5>
        <div class="row">
            <div class="col-xs-6 form-group">
                <label>Desde</label>
                <input type="text" class="form-control calendar" name="date_from" id="date_from" value="<?php echo date("1-m-Y");?>" readonly="readonly">
            </div>
            <div class="col-xs-6 form-group">
                <label>Desde</label>
                <input type="text" class="form-control calendar" name="date_to" id="date_to" readonly="readonly" value="<?php echo date("d-m-Y");?>">
            </div>
        </div> 
        `, 'goSales()');
        $(".calendar").datepicker({
                changeMonth: true,
                dateFormat: 'dd-mm-yy',
                changeYear: true
            });
    }
    function goSales(){
        var date_from=$('#date_from').val();
        var date_to=$('#date_to').val();
        location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'stats','action'=>'sales'),null,true);?>/date_from/'+date_from+'/date_to/'+date_to;
    }
</script>