<?php echo $this->render('_alert.phtml'); ?>
<ol class="breadcrumb">
    <li><a href="<?php echo $this->url(array('controller' => 'sinister', 'action' => 'account'), NULL, TRUE); ?>">Mi cuenta</a></li>
    <li class="active"><?php echo $this->login["co_user"]; ?></li>
</ol>
<div class="panel panel-default hidden-print">
    <div class="panel-heading panel-title text-center">
        Datos Generales
    </div>
    <div class="panel-body">
        <form method="POST">
            <div class="row">
                <div class="col-sm-4 form-group">
                    <label>Nombre *</label>
                    <input disabled="disabled" class="form-control" value="<?php echo $this->login["co_name"]; ?>">
                </div>
                <div class="col-sm-4 form-group">
                    <label>Teléfono</label>
                    <input class="form-control" value="<?php echo $this->login["co_phone"]; ?>" name="co_phone" placeholder="Teléfono">
                </div>
                <div class="col-sm-4 form-group">
                    <label>E-Mail</label>
                    <input class="form-control" value="<?php echo $this->login["co_email"]; ?>" name="co_email" placeholder="E-Mail">
                </div>
                <div class="col-sm-4 form-group">
                    <label>Usuario *</label>
                    <input class="form-control" value="<?php echo $this->login["co_user"]; ?>" name="co_user">
                </div>
                <div class="col-sm-4 form-group">
                    <label>Contrseña *</label>
                    <input class="form-control" value="" type="password" name="co_pass1" placeholder="******">
                </div>
                <div class="col-sm-4 form-group">
                    <label>Repita contraseña *</label>
                    <input class="form-control" value="" type="password" name="co_pass2" placeholder="******">
                </div>
            </div>
            <hr>
            <div class="btn-group">
                <button class="btn btn-default btn-sm" type="button" onclick="location.href = '<?php echo $this->url(array('action' => 'index')); ?>'">Cancelar</button>
                <button class="btn btn-primary btn-sm" type="submit">Aceptar</button>
            </div>
        </form>
    </div>
</div>