<?php echo $this->headLink()->appendStylesheet('https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css');?>
<?php echo $this->headLink()->appendStylesheet('https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css');?>
<table id="example" class="table table-striped table-bordered" style="width:100%"></table>
<?php echo $this->headScript()->prependFile('https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js', 'text/javascript');?>
<script>
    $(document).ready(function() {
        $('#example').on('preXhr.dt', function (e, settings, data) {
            sortColumns = [];
            directionColumns = [];
            for (let i = 0; i < data.order.length; i++) {
                col = data.order[i].column;
                dir = data.order[i].dir;
                sortColumns.push(data.columns[col].data);
                directionColumns.push(dir);
            }
            data.sort = sortColumns.join();
            data.direction = directionColumns.join();
        });
        $('#example').DataTable( {
            order: [[ 1, 'ASC' ]],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'
            },
            pageLength: 15,
            lengthMenu: [15, 50, 100],
            processing: true,
            serverSide: true,
            ajax: {
                url: "<?php echo $this->url(['module'=>'api','controller'=>'productors','action'=>'index']);?>",
                dataSrc: "data"
            },
            columns: [
                { title: "ID",data: "pr_id" },
                { title: "Nombre",data: "pr_name" },
                { title: "E-Mail",data: "pr_email" },
                { title: "Contraseña",data: "pr_password" },
                {
                    data: null,
                    orderable: false,
                    className: "text-center",
                    render: function (data, type, row) 
                    {
                        return `
                            <a title="Editar" class="glyphicon glyphicon-glyphicon glyphicon-edit btn-edit text-primary" href="javascript:void(0)"></a>
                            <a title="Orden de Trabajo" class="glyphicon glyphicon-glyphicon glyphicon-ban-circle text-danger" href="javascript:openDialog('<?php echo $this->messageDelete;?>','deleteRow(${data.pr_id})');"></a>
                        `;
                    }
                }
            ]
        } );
        $('#example').on('click', '.btn-edit', function () {
            var data = $('#example').DataTable().row( $(this).parents('tr') ).data();
            location.href='<?php echo $this->url(['action'=>'edit','id'=>''])?>'+data.pr_id;
        });
    } );

    
    function deleteRow(id) {
        console.log(id);
        $.ajax({
            url: '<?php echo $this->url(array('module' => 'api', 'controller' => 'productors', 'action' => 'delete','id'=>''), '', true); ?>'+id,
            type: 'DELETE',
            crossDomain: true,
            success: function(data) {
                location.reload();
            },  
            complete:function(){
            },
            error: function(data, status, error) {
            }
        });
    }
</script>