<form method="POST" action="<?php echo $this->url(array('action' => 'receive')); ?>">
    <div class="col-xs-9 form-group">
        <label>Producto</label>
        <select class="form-control autocomplete" name="type"  id="type">
            <option value=""></option>
            <?php foreach ($this->accesories as $key => $type): ?>
                    <option value="<?php echo $key; ?>"><?php echo $type; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="col-xs-3 form-group">
        <label>Cantidad</label>
        <select class="form-control" name="amount">
            <?php for ($i = 1; $i <= MAX_AMOUNT; $i++): ?>
                <option value="<?php echo $i ?>"><?php echo $i ?></option>
            <?php endfor; ?>
        </select>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-12 text-right">
        <hr class="btn-save">
        <div class="btn-group btn-save " >
            <button class="btn btn-default" onclick="window.parent.closeModal();">Cancelar</button>
            <button class="btn btn-primary" type="submit">Aceptar</button>
        </div>
    </div>
</form>