<div id="response">
    <?php
    $count_stock = time();
        ?>
        <div class="panel panel-default" id='<?php echo $count_stock; ?>'>
            <input type="hidden" name="count[]" value="1">
            <div class="panel-body relative">
                <div class="row">
                    <input type="hidden" name="amount[<?php echo $this->result['type']; ?>]" value="<?php echo $this->result['amount']; ?>">
                    <?php if ($this->formDisabled == true): ?>
                        <a href="javascript:void(0);">
                            <span class="glyphicon glyphicon-minus-sign"></span>
                        </a>
                    <?php else: ?>
                        <a class="icon-remove" href="javascript:removeReplacement('<?php echo $count_stock; ?>')">
                            <span class="glyphicon glyphicon-minus-sign text-danger"></span>
                        </a>
                    <?php endif; ?>
                    <div class="form-group col-xs-9">
                        <label>Producto</label>
                        <label class="detail">
                            [<?php echo $this->result['accesory']['ac_code']; ?>] - <?php echo $this->result['accesory']['ac_name']; ?>
                        </label>
                    </div>
                    <div class="form-group col-xs-1">
                        <label>Cantidad</label>
                        <label class="detail text-center"><b><?php echo $this->result['amount']; ?></b></label>
                    </div>
                    <div class="form-group col-xs-2">
                        <label>Stock</label>
                        <select class="form-control" onchange="showDiv(this.value, '#nostock<?php echo $count_stock; ?>');" name="stock[<?php echo $this->result['type']; ?>]" <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?>>
                            <option value="1">SI</option>
                            <option value="0">NO</option>
                        </select>
                    </div>
                </div>
                <div class="row" id="nostock<?php echo $count_stock; ?>" style="display: none;">
                    <div class="form-group col-xs-5">
                        <label>Proveedor</label>
                        <select class="form-control" name="sa_pr_id[<?php echo $this->result['type']; ?>]">
                            <?php foreach ($this->providers as $company): ?>
                                <option value="<?php echo $company['pr_id'] ?>"><?php echo $company['pr_name'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-xs-2">
                        <label>Fecha Pedido</label>
                        <input type="text" class="form-control calendar" name="sa_date_from[<?php echo $this->result['type']; ?>]">
                    </div>
                    <div class="form-group col-xs-2">
                        <label>Fecha llegada</label>
                        <input type="text" class="form-control calendar" name="sa_date[<?php echo $this->result['type']; ?>]">
                    </div>
                    <div class="form-group col-xs-3">
                        <label>Medio</label>
                        <input type="text" class="form-control" name="sa_transport[<?php echo $this->result['type']; ?>]">
                    </div>
                </div>
                <div class="row" >
                    <div class="form-group col-xs-5">
                        <label>Nº Remito</label>
                        <input type="text" class="form-control" name="sa_number[<?php echo $this->result['type']; ?>]">
                    </div>
                    <div class="form-group col-xs-2">
                        <label>Precio Costo</label>
                        <input type="text" class="form-control" name="sa_price_cost[<?php echo $this->result['type']; ?>]">
                    </div>
                    <div class="form-group col-xs-2">
                        <label>Precio Venta</label>
                        <input type="text" class="form-control" name="sa_price_sale[<?php echo $this->result['type']; ?>]">
                    </div>
                </div>
            </div>
        </div>
</div>
<script>
    window.parent.addReplacement(document.getElementById('response').innerHTML);
    window.parent.closeModal();
</script>