<blockquote>
    <?php if ($this->title) { ?>
        <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
    <?php } ?>
    <?php if ($this->description) { ?>
        <small class="visible-lg visible-md visible-sm"><?php echo $this->description ?></small>
    <?php } ?>
</blockquote>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                Siniestros
            </div>
            <div class="panel-body">
                <table class="table table-striped table-condensed table-hover">
                    <tr>
                        <th>ID Siniestro</th>
                        <th class="text-center">Número</th>
                        <th>Fecha</th>
                        <th>Asegurado</th>
                        <th>Compañia</th>
                        <th>Estado</th>
                    </tr>
                    <?php foreach ($this->result as $order): ?>
                    <tr onclick="location.href='<?php echo $this->url(array('controller' => 'sinister', 'action' => 'detail', 'id' => $order["si_id"])); ?>'">
                            <td><b> #<?php echo $order["si_id"] ?></b></td>
                            <td><?php echo $order["si_number"] ?></td>
                            <td><?php echo $order["si_date"] ?></td>
                            <td><?php echo $order["si_fullname"] ?></td>
                            <td><?php echo $order["co_name"] ?></td>
                            <td><?php echo $order["status_label"] ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>